#!/bin/sh

set -eu

QEMU=$(command -v qemu-system-x86_64)
QEMU_ARGS="${QEMU_ARGS-} -smp ${QEMU_CPU} -m ${QEMU_RAM}"
QEMU_ARGS="${QEMU_ARGS-} -vga std -display vnc=unix:/run/qemu-haiku.socket"
QEMU_ARGS="${QEMU_ARGS-} -hda /var/lib/qemu/images/haiku.img"
QEMU_ARGS="${QEMU_ARGS-} -cdrom /var/lib/qemu/iso/haiku.iso"
QEMU_ARGS="${QEMU_ARGS-} -boot c"
QEMU_ARGS="${QEMU_ARGS-} -usb -device usb-tablet"
QEMU_ARGS="${QEMU_ARGS-} -netdev user,id=n0,hostfwd=tcp::6022-:22 -device rtl8139,netdev=n0"
if [ "${QEMU_KVM}" = true ]; then QEMU_ARGS="${QEMU_ARGS-} -enable-kvm"; fi

cd ~/
exec 2>&1
exec "${QEMU}" ${QEMU_ARGS}
