image: docker:stable

services:
  - docker:dind

stages:
  - build:images
  - push:images

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

build:image:
  stage: build:images
  before_script:
    - docker info
    - apk add --no-cache coreutils git make
  script:
    - make build-image save-image
  artifacts:
    expire_in: 1 hour
    paths:
      - dist/

push:image:
  stage: push:images
  before_script:
    - apk add --no-cache coreutils git make
    - docker login -u "${CI_DEPLOY_USER}" -p "${CI_DEPLOY_PASSWORD}" "${CI_REGISTRY}" >/dev/null 2>&1
  script:
    - make load-image push-image
  only:
    - /^v([0-9.]+)(-.+)?$/
  except:
    - branches
  dependencies:
    - build:image
