stages:
  - "build:images"
  - "push:images"

variables:
  DOCKER_HOST: "tcp://dockerd:2376"
  DOCKER_TLS_SAN: "DNS:dockerd"
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: "overlay2"

default:
  image: "docker.io/docker:stable"
  services:
    - name: "docker.io/docker:dind"
      alias: "dockerd"

build:images:native:
  stage: "build:images"
  before_script:
    - "apk add --no-cache coreutils git make xz"
  script:
    - "make build-native-image save-native-image"
  artifacts:
    expire_in: "1 day"
    paths:
      - "./dist/"

push:images:native:
  stage: "push:images"
  dependencies:
    - "build:images:native"
  only:
    - "/^v[0-9]+$/"
  before_script:
    - "apk add --no-cache coreutils git make xz"
    - "docker login -u \"${CI_REGISTRY_USER:?}\" -p \"${CI_REGISTRY_PASSWORD:?}\" \"${CI_REGISTRY:?}\""
  script:
    - "make load-image push-image"
